<?php

namespace Plu\PhorgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateMetaRepository extends EntityRepository
{
}
