<?php

namespace Plu\PhorgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRelationRepository extends EntityRepository
{
}
